[tool.briefcase]
project_name = "tip"
bundle = "com.dev"
version = "0.0.1"
url = "https://dev.com/lo"
license = "Apache Software License"
author = 'Devdisa'
author_email = "dabdissanayake@gmail.com"

[tool.briefcase.app.tipcalculator]
formal_name = "tip"
description = "hfgsdfbgdsbgd"
icon = "src/tipcalculator/resources/tipcalculator"
sources = ['src/tipcalculator']
requires = [
]


[tool.briefcase.app.tipcalculator.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.tipcalculator.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.tipcalculator.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.tipcalculator.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.tipcalculator.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

# Mobile deployments
[tool.briefcase.app.tipcalculator.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.tipcalculator.android]
requires = [
    'toga-android>=0.3.0.dev38'
]

[tool.briefcase.app.tipcalculator.web]
requires = [
    # Workaround; toga-web 0.3.0.dev38 doesn't include toga-core as a dependency.
    "toga-core>=0.3.0.dev38",
    "toga-web>=0.3.0.dev38",
]
style_framework = "Bootstrap v4.6"
